name: 'Terraform Init and Plan'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.4.0' # Specify the Terraform version you need

    - name: Terraform Init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Terraform Plan
      id: terraform-plan
      run: terraform plan -out=tfplan
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Publish Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan

    - name: Create String Output
      id: tf-plan-string
      run: |
        TERRAFORM_PLAN=$(terraform show -no-color tfplan)
        delimiter="$(openssl rand -hex 8)"
        echo "summary<<${delimiter}" >> $GITHUB_ENV
        echo "## Terraform Plan Output" >> $GITHUB_ENV
        echo "<details><summary>Click to expand</summary>" >> $GITHUB_ENV
        echo "" >> $GITHUB_ENV
        echo '```terraform' >> $GITHUB_ENV
        echo "$TERRAFORM_PLAN" >> $GITHUB_ENV
        echo '```' >> $GITHUB_ENV
        echo "</details>" >> $GITHUB_ENV
        echo "${delimiter}" >> $GITHUB_ENV

    - name: Publish Terraform Plan to Task Summary
      run: |
        echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
